version: '2'
services:
    botportal-app:
        image: botportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://botportal-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=botportal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    botportal-mongodb:
        extends:
            file: mongodb.yml
            service: botportal-mongodb
